### ISSUE TITLE
Grouper for '<class 'pandas.core.frame.DataFrame'>' not 1-dimensional

### ISSUE THREAD

**Issue by ghost** [jamalmoir/notebook_playground#1]
Whenever I get to the point to run `new_areas = pd.DataFrame(new.groupby(new.postcode.str.extract(r'(\D+)')).postcode.count())` I receive the following value error: 

> ValueError: Grouper for '<class 'pandas.core.frame.DataFrame'>' not 1-dimensional

Any idea why this is the case? Any help is much appreciated!

**Comment by jamalmoir** [comment]
@sanojnesnub Hello, thanks for submitting an issue. I'll take a look at this today. I wrote this script a while ago so packages might have had breaking updates.

I'll push a fix if that is the case.

**Comment by jamalmoir** [comment]
I went ahead and pushed a fix for it. @sanojnesnub

**Comment by ghost** [comment]
I'll check it out as soon as possible. Thank you very much!!

**Comment by ghost** [comment]
Seems to work! Great, thank you!

**Comment by jamalmoir** [comment]
@sanojnesnub Fantastic, again, thanks for creating the issue.
